version: '3.8'

services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: "test|test12345_"
      ADDRESS: "localhost"
    volumes:
      - ~/workspace/studies/cos332/linux/p8/ftp/test:/ftp/test